### ISSUE TITLE
Change background color?

### ISSUE THREAD

**Issue by luckman212** [gregzuro/obsidian-kroki#2]
Is it possible to change or specify the background color used for the graphs?

With a dark theme, it becomes impossible to read them unfortunately.  It would be cool if we could specify a bgcolor. Maybe it's possible with CSS, not sure

![image](https://user-images.githubusercontent.com/1992842/125172569-71718900-e188-11eb-9601-e504c2198577.png)

**Comment by luckman212** [comment]
I found a CSS hack that seems to work...

```css
.markdown-preview-view div[class|="block-language"] {
  background-color: #cfcfcf;
}
```
![image](https://user-images.githubusercontent.com/1992842/125173097-463c6900-e18b-11eb-8a0e-e2c5deaf09db.png)

**Comment by gregzuro** [comment]
> I found a CSS hack that seems to work...

This is great! Thanks.

I'll look into incorporating something like this.

**Comment by netthier** [comment]
Any updates on this? I'm having problems viewing some of my diagrams in dark mode.

**Comment by subsonicpulse** [comment]
add `dest.style.backgroundColor = 'white';` after `const dest = document.createElement('div');` on line 6883 in installed plugin:
folder: `Obsidian Vault\.obsidian\plugins\obsidian-kroki`, file: `main.ts`

Original Source: after line 54.

Some setting would be nice. But currently i have no time to find out how to do it. 

Hope that helps you. For me its fine now with Dark Mode.

**Comment by subsonicpulse** [comment]
> Any updates on this? I'm having problems viewing some of my diagrams in dark mode.

Please my comment. That should help you.

**Comment by subsonicpulse** [comment]
> Any updates on this? I'm having problems viewing some of my diagrams in dark mode.

add dest.style.backgroundColor = 'white'; after const dest = document.createElement('div'); on line 6883 in installed plugin:
folder: Obsidian Vault\.obsidian\plugins\obsidian-kroki, file: main.ts

Original Source: after line 54.

Some setting would be nice. But currently i have no time to find out how to do it.

Hope that helps you. For me its fine now with Dark Mode.

**Comment by julianmueller** [comment]
maybe there is an even nicer way to just flip the colors and leave the background transparent? But I guess this is a core of th kroki engine?

I created my own css snippet which does the major work (but will mess up some colored diagrams!):

```css
/* for adjusting to light/dark theme */

div[class^="block-language-"] svg {
    /* background: var(--background-primary) !important; */
    background: none !important;
}

div[class^="block-language-"] svg text {
    fill: var(--text-normal) !important;
}

div[class^="block-language-"] svg path {
    stroke: var(--text-normal) !important;
}

div[class^="block-language-"] svg rect {
    fill: var(--background-primary) !important;
    stroke: var(--text-normal) !important;
}

div[class^="block-language-"] svg circle {
    fill: var(--background-primary) !important;
    stroke: var(--text-normal) !important;
}

div[class^="block-language-"] svg polygon {
    fill: var(--background-primary) !important;
    stroke: var(--text-normal) !important;
}

svg[id^="mermaid-"] {
    /* font-size: var(--font-text-size); */
    /* font-family: var(--font-text); */
    color: var(--text-normal) !important;
}
```
